### register request
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "amirrasooli3",
    "email": "amirrasooli3@gmail.com",
    "mobile": "09127173429",
    "password": "1234567",
    "confirm_password": "1234567"

}

### login request
POST  http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username": "amirrasooli3",
    "password": "1234567"


}